/**
 * TIN chart identity, rendering constants, static metadata, and fresh config.
 */

const COLOR = '#5d8aa8';

export const TIN_COLOR_RAMPS = Object.freeze([
  'custom',
  'viridis',
  'plasma',
  'magma',
  'inferno',
  'turbo',
  'terrain',
  'grays',
]);

export const TIN_CHART = {
  defaultFillMode: 'smooth',
  defaultColorRamp: 'custom',
  defaultSubdivisionDepth: 3,
  minSubdivisionDepth: 0,
  maxSubdivisionDepth: 4,
  rampBuckets: 128,
  maxSurfaceLeaves: 262144,
  defaultPointRadius: 3,
  defaultEdgeColor: '#5f5a53',
  defaultHullColor: '#3f3a33',
  defaultShowEdges: true,
  defaultShowPoints: true,
  defaultShowZLabels: false,
  defaultShowHull: false,
  defaultShowIsolines: false,
  defaultIsolineMode: 'count',
  defaultIsolineCount: 5,
  minIsolineCount: 2,
  maxIsolineCount: 20,
  defaultIsolineStep: 1,
  maxIsolineLevels: 200,
  defaultIsolineColor: '#1f2937',
  defaultIsolineWidth: 0.8,
  minIsolineWidth: 0.5,
  maxIsolineWidth: 2,
  defaultColorIsolinesByZ: false,
  defaultIsolineMinColor: '#1e40af',
  defaultIsolineMaxColor: '#dc2626',
  defaultShowIsolineLabels: false,
  defaultIsolineLabelSize: 10,
  minIsolineLabelSize: 8,
  maxIsolineLabelSize: 14,
  defaultIsolineLabelColor: '#1f2937',
  defaultShowThreshold: false,
  defaultThresholdValue: 0,
  defaultThresholdColor: '#dc2626',
  defaultThresholdWidth: 2,
  minThresholdWidth: 0.5,
  maxThresholdWidth: 4,
};

function createDefaultConfig() {
	return {
		enabled: false,
		expanded: false,
		x: null,
		y: null,
		z: null,
		customTitle: '',
		chartHeight: 460,
		fillMode: TIN_CHART.defaultFillMode,
		subdivisionDepth: TIN_CHART.defaultSubdivisionDepth,
		colorRamp: TIN_CHART.defaultColorRamp,
		gradientMinColor: COLOR,
		gradientMaxColor: '#ffffff',
		gradientDistribution: 'value',
		colorScheme: 'Colorblind-Safe',
		showEdges: TIN_CHART.defaultShowEdges,
		edgeColor: TIN_CHART.defaultEdgeColor,
		showPoints: TIN_CHART.defaultShowPoints,
		pointRadius: TIN_CHART.defaultPointRadius,
		showZLabels: TIN_CHART.defaultShowZLabels,
		showHull: TIN_CHART.defaultShowHull,
		hullColor: TIN_CHART.defaultHullColor,
		showIsolines: TIN_CHART.defaultShowIsolines,
		isolineMode: TIN_CHART.defaultIsolineMode,
		isolineCount: TIN_CHART.defaultIsolineCount,
		isolineStep: TIN_CHART.defaultIsolineStep,
		isolineColor: TIN_CHART.defaultIsolineColor,
		isolineWidth: TIN_CHART.defaultIsolineWidth,
		colorIsolinesByZ: TIN_CHART.defaultColorIsolinesByZ,
		isolineMinColor: TIN_CHART.defaultIsolineMinColor,
		isolineMaxColor: TIN_CHART.defaultIsolineMaxColor,
		showIsolineLabels: TIN_CHART.defaultShowIsolineLabels,
		isolineLabelSize: TIN_CHART.defaultIsolineLabelSize,
		isolineLabelColor: TIN_CHART.defaultIsolineLabelColor,
		showThreshold: TIN_CHART.defaultShowThreshold,
		thresholdValue: TIN_CHART.defaultThresholdValue,
		thresholdColor: TIN_CHART.defaultThresholdColor,
		thresholdWidth: TIN_CHART.defaultThresholdWidth,
		showXAxisLabel: true,
		showYAxisLabel: true,
	};
}

export const TIN_DEFINITION = Object.freeze({
	key: 'tin',
	color: COLOR,
	dimensions: {
		width: 700,
		height: 460,
		margins: {
			top: 16,
			right: 16,
			bottom: 44,
			left: 56,
		},
	},
	heightLimits: { min: 220, max: 900 },
	workspaceIds: {
		container: 'chart-tin-container',
		block: 'chart-block-tin',
	},
	catalogCategoryKey: 'chive-viz-category-spatial',
	createDefaultConfig,
});
