blank_issues_enabled: false
contact_links:
  - name: Question or Q&A
    url: https://github.com/GabrielInada/CHIVE/discussions/new
    about: For questions that aren't bug reports or feature proposals, start a Discussion instead.
