import { BAR_CHART, BUBBLE_CHART, CHART_COLORS, LINE_CHART, NETWORK_GRAPH, PIE_CHART, SCATTER_PLOT, TIN_CHART, TREEMAP_CHART } from './charts.js';
import { normalizeGlobalFilter, createEmptyGlobalFilter } from '../utils/globalFilter.js';

export function createDefaultChartConfig() {
	return {
		aba: 'preview',
		globalFilter: createEmptyGlobalFilter(),
		bar: {
			enabled: false,
			category: null,
			expanded: false,
			customTitle: '',
			chartHeight: 320,
			sort: BAR_CHART.defaultSort,
			topN: BAR_CHART.defaultTopN,
			color: CHART_COLORS.bar,
			colorMode: 'uniform',
			colorScheme: 'Colorblind-Safe',
			gradientMinColor: CHART_COLORS.bar,
			gradientMaxColor: '#ffffff',
			gradientDistribution: 'value',
			manualThresholdPct: 50,
			showXAxisLabel: true,
			showYAxisLabel: true,
			measureMode: BAR_CHART.defaultMeasureMode,
			valueColumn: null,
		},
		scatter: {
			enabled: false,
			x: null,
			y: null,
			expanded: false,
			customTitle: '',
			chartHeight: 320,
			xScale: SCATTER_PLOT.defaultScale,
			yScale: SCATTER_PLOT.defaultScale,
			radius: SCATTER_PLOT.defaultRadius,
			opacity: SCATTER_PLOT.defaultOpacity,
			sizeMode: 'uniform',
			sizeField: null,
			sizeMin: 2,
			sizeMax: 12,
			categoricalPairMode: 'jitter',
			color: CHART_COLORS.scatter,
			colorMode: 'uniform',
			colorField: null,
			colorFieldType: null,
			gradientMinColor: CHART_COLORS.scatter,
			gradientMaxColor: '#ffffff',
			gradientDistribution: 'value',
			colorScheme: 'Colorblind-Safe',
			showXAxisLabel: true,
			showYAxisLabel: true,
			regression: {
				enabled: false,
				mode: 'overall',
				showLine: true,
				showCI: true,
				showEquation: true,
				showR2: true,
				lineWidth: 2,
				lineOpacity: 0.9,
				bandOpacity: 0.18,
				overallColor: null,
			},
		},
		network: {
			enabled: false,
			expanded: false,
			customTitle: '',
			chartHeight: 420,
			source: null,
			target: null,
			weight: null,
			group: null,
			nodeRadius: NETWORK_GRAPH.defaultNodeRadius,
			linkDistance: NETWORK_GRAPH.defaultLinkDistance,
			chargeStrength: NETWORK_GRAPH.defaultChargeStrength,
			linkOpacity: NETWORK_GRAPH.defaultLinkOpacity,
			zoomScale: NETWORK_GRAPH.defaultZoomScale,
			alphaDecay: NETWORK_GRAPH.defaultAlphaDecay,
			showLegend: true,
			showNodeLabels: false,
			colorScheme: 'Colorblind-Safe',
			sourceNodeColor: '#e3743d',
			targetNodeColor: '#6b94c9',
			edgeColorMode: 'gradient',
		},
		pie: {
			enabled: false,
			category: null,
			measureMode: 'count',
			valueColumn: null,
			expanded: false,
			customTitle: '',
			chartHeight: 360,
			innerRadius: PIE_CHART.defaultInnerRadius,
			outerRadius: PIE_CHART.defaultOuterRadius,
			padAngle: PIE_CHART.defaultPadAngle,
			zoomScale: PIE_CHART.defaultZoomScale,
			topN: PIE_CHART.defaultTopN,
			topNMode: PIE_CHART.defaultTopNMode,
			color: CHART_COLORS.pie,
			showCategoryLabel: true,
			showValueLabel: true,
			showLegend: true,
			labelPosition: 'inside',
			colorMode: 'uniform',
			colorScheme: 'Colorblind-Safe',
			customSliceColors: {},
		},
		treemap: {
			enabled: false,
			category: null,
			measureMode: TREEMAP_CHART.defaultMeasureMode,
			valueColumn: null,
			topN: TREEMAP_CHART.defaultTopN,
			padding: TREEMAP_CHART.defaultPadding,
			expanded: false,
			customTitle: '',
			chartHeight: 380,
			color: CHART_COLORS.treemap,
			colorMode: 'scheme',
			colorScheme: 'Colorblind-Safe',
			showLabels: true,
			showValues: true,
		},
		bubble: {
			enabled: false,
			expanded: false,
			category: null,
			groupColumn: null,
			nestingColumns: [],
			customTitle: '',
			chartHeight: 700,
			topN: BUBBLE_CHART.defaultTopN,
			measureMode: BUBBLE_CHART.defaultMeasureMode,
			valueColumn: null,
			padding: BUBBLE_CHART.defaultPadding,
			labelMode: BUBBLE_CHART.defaultLabelMode,
			nestingMode: BUBBLE_CHART.defaultNestingMode,
			colorScheme: 'Tableau10',
		},
		line: {
			enabled: false,
			expanded: false,
			x: null,
			y: null,
			customTitle: '',
			chartHeight: 320,
			curve: LINE_CHART.defaultCurve,
			missingMode: LINE_CHART.defaultMissingMode,
			strokeWidth: LINE_CHART.defaultStrokeWidth,
			color: CHART_COLORS.line,
			ghostStrokeColor: LINE_CHART.defaultGhostStrokeColor,
			showPoints: LINE_CHART.defaultPointsVisible,
			sortX: LINE_CHART.defaultSortX,
			aggregateMode: LINE_CHART.defaultAggregateMode,
			showXAxisLabel: true,
			showYAxisLabel: true,
		},
		tin: {
			enabled: false,
			expanded: false,
			x: null,
			y: null,
			z: null,
			customTitle: '',
			chartHeight: 460,
			fillMode: TIN_CHART.defaultFillMode,
			subdivisionDepth: TIN_CHART.defaultSubdivisionDepth,
			colorRamp: TIN_CHART.defaultColorRamp,
			gradientMinColor: CHART_COLORS.tin,
			gradientMaxColor: '#ffffff',
			gradientDistribution: 'value',
			colorScheme: 'Colorblind-Safe',
			showEdges: TIN_CHART.defaultShowEdges,
			edgeColor: TIN_CHART.defaultEdgeColor,
			showPoints: TIN_CHART.defaultShowPoints,
			pointRadius: TIN_CHART.defaultPointRadius,
			showZLabels: TIN_CHART.defaultShowZLabels,
			showHull: TIN_CHART.defaultShowHull,
			hullColor: TIN_CHART.defaultHullColor,
			showIsolines: TIN_CHART.defaultShowIsolines,
			isolineMode: TIN_CHART.defaultIsolineMode,
			isolineCount: TIN_CHART.defaultIsolineCount,
			isolineStep: TIN_CHART.defaultIsolineStep,
			isolineColor: TIN_CHART.defaultIsolineColor,
			isolineWidth: TIN_CHART.defaultIsolineWidth,
			colorIsolinesByZ: TIN_CHART.defaultColorIsolinesByZ,
			isolineMinColor: TIN_CHART.defaultIsolineMinColor,
			isolineMaxColor: TIN_CHART.defaultIsolineMaxColor,
			showIsolineLabels: TIN_CHART.defaultShowIsolineLabels,
			isolineLabelSize: TIN_CHART.defaultIsolineLabelSize,
			isolineLabelColor: TIN_CHART.defaultIsolineLabelColor,
			showThreshold: TIN_CHART.defaultShowThreshold,
			thresholdValue: TIN_CHART.defaultThresholdValue,
			thresholdColor: TIN_CHART.defaultThresholdColor,
			thresholdWidth: TIN_CHART.defaultThresholdWidth,
			showXAxisLabel: true,
			showYAxisLabel: true,
		},
	};
}

function pickGlobalFilter(config) {
	if (!config || typeof config !== 'object') {
		return createEmptyGlobalFilter();
	}
	return normalizeGlobalFilter(config.globalFilter);
}

export function mergeChartConfigWithDefaults(configGraficos) {
	const defaults = createDefaultChartConfig();
	const config = configGraficos || {};

	return {
		...defaults,
		...config,
		globalFilter: pickGlobalFilter(config),
		bar: {
			...defaults.bar,
			...(config.bar || {}),
		},
		scatter: {
			...defaults.scatter,
			...(config.scatter || {}),
			regression: {
				...defaults.scatter.regression,
				...((config.scatter && config.scatter.regression) || {}),
			},
		},
		network: {
			...defaults.network,
			...(config.network || {}),
		},
		pie: {
			...defaults.pie,
			...(config.pie || {}),
		},
		treemap: {
			...defaults.treemap,
			...(config.treemap || {}),
		},
		bubble: (() => {
			const merged = { ...defaults.bubble, ...(config.bubble || {}) };
			if (Array.isArray(merged.nestingColumns) && merged.nestingColumns.length > 0) {
				// nestingColumns already set, keep it
			} else if (merged.groupColumn && typeof merged.groupColumn === 'string') {
				merged.nestingColumns = [merged.groupColumn];
			} else {
				merged.nestingColumns = [];
			}
			return merged;
		})(),
		line: {
			...defaults.line,
			...(config.line || {}),
		},
		tin: {
			...defaults.tin,
			...(config.tin || {}),
		},
	};
}
